kind: pipeline
name: react-ci-cd

steps:
  - name: deps
    image: node:9-alpine
    commands:
      - npm install
  
  - name: build
    image: node:9-alpine
    commands:
      - npm run build
  
  - name: tests
    image: node:9-alpine
    commands:
      - npm test
  
  - name: pre-release
    image: node:9-alpine
    commands:
      - npm pack
  
  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - build.tar.gz
    when:
      event: tag

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
      channel: testperso
    when:
      status: [ success, failure ]
